# Generated by Django 4.2.3 on 2023-11-18 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="desciption",
            new_name="description",
        ),
    ]
